name: Copy Docker Image
on: 
  workflow_dispatch:
    inputs:
      source:
        description: 'https://hub.docker.com/layers/starrocks'     
        required: true
        default: 'hub.docker.com/layers/starrocks'
      destination:
        description: 'registry.cn-hangzhou.aliyuncs.com'
        required: true
        default: 'registry.cn-hangzhou.aliyuncs.com'
      source_repo:
        description: 'dev-env-centos7:3.1.11'
        required: true
        default: 'dev-env-centos7:3.1.11'
      destination_repo:
        description: 'starrocks/dev-env-centos7:3.1.11'
        required: true
        default: 'starrocks/dev-env-centos7:3.1.11'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Docker Images
      uses: ikrong/docker-sync-action@main
      with:
        source: ${{ github.event.inputs.source }}
        source-credential: ${{ secrets.SOURCE_CREDENTIAL }}
        destination: ${{ github.event.inputs.destination }}
        destination-credential: ${{ secrets.DESTINATION_CREDENTIAL }}
        copy: "${{ github.event.inputs.source_repo }} ${{ github.event.inputs.destination_repo }}"
